### ISSUE TITLE
Support consistent-sized image picker images

### ISSUE THREAD

**Issue by Alanaktion** [Alanaktion/proboot#8]
This is fairly easy, we could add something like this, which introduces a new `4:3` class for the main imagepicker element:

```scss
.imagecheck-4-3 {
    width: 100%;
    .imagecheck-figure {
        padding-bottom: 75%;
    }
    .imagecheck-image {
        position: absolute;
        object-fit: cover;
        width: 100%;
        height: 100%;
    }
}
```
